2024-01-24 14:02:35: Experiment log path in: D:\omer\ST-SSL\experiments\NYCBike1\20240124-140235
2024-01-24 14:02:35: Experiment configs are: Namespace(batch_size=32, best_path='None', d_input=1, d_model=64, d_output=1, data_dir='data', dataset='NYCBike1', debug=False, device='cuda', dropout=0.2, early_stop=True, early_stop_patience=15, epochs=100, grad_norm=True, graph_file='data/NYCBike1/adj_mx.npz', input_length=19, log_dir='D:\\omer\\ST-SSL\\experiments\\NYCBike1\\20240124-140235', lr_init=0.001, max_grad_norm=5, mode='train', nmb_prototype=6, num_nodes=128, percent=0.1, seed=31, shm_temp=0.5, temp=4, test_batch_size=32, use_dwa=True, yita=1)
2024-01-24 14:02:35: Traceback (most recent call last):
  File "main.py", line 59, in model_supervisor
    results = trainer.train() # best_eval_loss, best_epoch
  File "D:\omer\ST-SSL\model\trainer.py", line 109, in train
    train_epoch_loss, loss_t = self.train_epoch(epoch, loss_weights)
  File "D:\omer\ST-SSL\model\trainer.py", line 58, in train_epoch
    loss, sep_loss = self.model.loss(repr1, repr2, target, self.scaler, loss_weights)
  File "D:\omer\ST-SSL\model\models.py", line 62, in loss
    l1 = self.pred_loss(z1, z2, y_true, scaler)
  File "D:\omer\ST-SSL\model\models.py", line 80, in pred_loss
    (1 - self.args.yita) * self.mae(y_pred[..., 1], y_true[..., 1])
IndexError: index 1 is out of bounds for dimension 1 with size 1

